#!/bin/bash

cd fs/prog
# Read last 'line' even if there's no newline at the end
curl ledspire.local/prog 2>/dev/null | while read name || [ -n "$name" ]; do
	wget --quiet --show-progress "ledspire.local/prog/$name" -O "$name"
done
